create table if not exists public.user_interactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  movie_id integer not null,
  interaction_type text not null default 'click',
  score integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists user_interactions_user_id_idx
  on public.user_interactions(user_id);

create index if not exists user_interactions_movie_id_idx
  on public.user_interactions(movie_id);

alter table public.user_interactions enable row level security;

create policy "Users can read their own interactions"
on public.user_interactions
for select
using (auth.uid() = user_id);

create policy "Users can insert their own interactions"
on public.user_interactions
for insert
with check (auth.uid() = user_id);
